# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  email:
    recipients:
      - bonhomme.vincent@gmail.com
    on_success: change
    on_failure: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master


matrix:
  include:
    - dist: trusty
    - dist: xenial
      r_check_args: '' # because _R_CHECK_THINGS_IN_TEMP_DIR_ is broken
    - os: osx
      brew_packages: imagemagick ghostscript
    - os: osx
      brew_packages: imagemagick@6 ghostscript
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
    - dist: trusty
      r_check_args: '--ignore-vignettes'
      r_build_args: '--no-build-vignettes'
      addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
            - cargo
            - gsfonts

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts

bioc_packages: EBImage
